### ISSUE TITLE
send-btc: ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/toolkit#68]
npx hardhat send-btc --amount 0.001 --memo 629eEe97B95Bd6e04B0885De58eF016177a709Ae2cD3D070aE1BD365909dD859d29F387AA96911e1 --recipient tb1qy9pqmk2pd9sv63g27jt8r657wy0d9ueeh0nqur
An unexpected error occurred:

ReferenceError: fetch is not defined

**Comment by fadeev** [comment]
Works fine when the command is called in the toolkit repo, but I can reproduce the issue when using the tutorial.

**Comment by fadeev** [comment]
The issue I can reproduce is:

```
An unexpected error occurred:

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at Function.from (node:buffer:335:9)
    at SimpleTaskDefinition.main [as action] (/Users/fadeev/template/node_modules/@zetachain/toolkit/dist/tasks/sendBTC.js:114:46)
    at Environment._runTaskDefinition (/Users/fadeev/template/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:35)
    at Environment.run (/Users/fadeev/template/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:25)
    at main (/Users/fadeev/template/node_modules/hardhat/src/internal/cli/cli.ts:280:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Happens when you don't have a private key in `.env` (or an env variable).

**Comment by fadeev** [comment]
`fetch is not defined` can be resolved by upgrading Node.js to version 18.
