### ISSUE TITLE
Error when tracking CCTX

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/toolkit#91]
```
npx hardhat cctx 0x9abfa8452cad151a2db7e562e2dc878fd39783f95a8f372c4c22d39e9061ac65
✓ CCTXs on ZetaChain found.
/Users/fadeev/github.com/zeta-chain/toolkit/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:269878fd39783f95a8f372c4c22d39e9061ac65
        const error: any = new Error(message);
                           ^
Error: processing response error (body="{\"error\":{\"code\":-32000,\"message\":\"method handler crashed\"},\"id\":44,\"jsonrpc\":\"2.0\"}", error={"code":-32000}, requestBody="{\"method\":\"eth_getTransactionByHash\",\"params\":[\"0xdc3d4b78893493e77507d38f47117078dd04493a37840a3357f85c01c87a31d5\"],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://zetachain-athens-evm.blockpi.network/v1/rpc/public", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (/Users/fadeev/github.com/zeta-chain/toolkit/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/fadeev/github.com/zeta-chain/toolkit/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at /Users/fadeev/github.com/zeta-chain/toolkit/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/src.ts/index.ts:341:28
    at step (/Users/fadeev/github.com/zeta-chain/toolkit/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/Users/fadeev/github.com/zeta-chain/toolkit/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/Users/fadeev/github.com/zeta-chain/toolkit/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by fadeev** [comment]
Has been fixed in the latest toolkit.
